# -*- coding: utf-8 -*-
"""salary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xId9j_8Bwu_AK9HOLcW69VlKoJXAMc3s
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

# salaries = pd.read_csv("/content/Salaries.csv")



from google.colab import drive
drive.mount('/content/drive')

salaries = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Salaries.csv")

salaries.info()

salaries.head()



for col in ['BasePay', 'OvertimePay', 'OtherPay', 'Benefits']:
        salaries[col] = pd.to_numeric(salaries[col], errors='coerce')

salaries.head()

pay_columns = salaries.columns[3:salaries.columns.get_loc('Year')]

salaries.head()

pay_columns

pays_arrangement = list(zip(*(iter(pay_columns),) * 3))

pays_arrangement

salaries.head()

fig, axes = plt.subplots(2,3)



for i in range(len(pays_arrangement)):
    for j in range(len(pays_arrangement[i])):
        f = salaries[pays_arrangement[i][j]]
        pd.DataFrame.hist(pd.DataFrame(f),rwidth = 0.6)

fig ,axes = plt.subplots(2,3)

for i in range(len(pays_arrangement)):
    for j in range(len(pays_arrangement[i])):
                   
                   pd.DataFrame(salaries[pays_arrangement[i][j]]).hist(ax = axes[i,j],rwidth = 0.5)
                   axes[i,j].set_title(pays_arrangement[i][j])
plt.show()

fig.set_figheight(5)
fig.set_figheight(12)

fig ,axes = plt.subplots(2,3)

for i in range(len(pays_arrangement)):
    for j in range(len(pays_arrangement[i])):
                   
                   pd.DataFrame(salaries[pays_arrangement[i][j]]).hist(ax = axes[i,j],rwidth = 0.5)
                   axes[i,j].set_title(pays_arrangement[i][j])
                    
plt.subplots_adjust(hspace = 1)
plt.subplots_adjust(wspace = 1)
plt.show()

fig ,axes = plt.subplots(2,3)

for i in range(len(pays_arrangement)):
    for j in range(len(pays_arrangement[i])):
                   
                   pd.DataFrame(salaries[pays_arrangement[i][j]]).hist(ax = axes[i,j],rwidth = 0.5)
                   axes[i,j].set_title(pays_arrangement[i][j])
                   axes[i,j].set_xticklabels(labels=axes[i,j].get_xticks(),rotation = 30)
                    
plt.subplots_adjust(hspace = 1)
plt.subplots_adjust(wspace = 1)
plt.show()